name: Daily Action at 8-55 PM IST
 
on:
  schedule:
    - cron: '10 22 * * *'  # This is in UTC, so it's 9 PM IST (India/Kolkata)
  #timezone: 'Asia/Kolkata'  # Set the timezone to IST
 
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a script
        run: echo "This action runs every day at 9 PM IST!"
