---
name: Scheduled Workflow

# Define the trigger to run on a schedule
on:
  schedule:
    # Cron syntax: Minute Hour Day-of-Month Month Day-of-Week
    # This is set to trigger at 12:25 PM UTC (5:55 PM IST)
    - cron: "30 12 * * *"

jobs:
  scheduled-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run a sample script
      run: |
        echo "Scheduled workflow triggered at $(date)"
        echo "Hello, GitHub Actions from a scheduled workflow!"
