name: Scheduled Workflow

on:
  schedule:
    - cron: "25 12 * * *"

jobs:
  scheduled-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run a sample script
      run: |
        echo "Scheduled workflow triggered at $(date)"
        echo "Hello, GitHub Actions from a scheduled workflow!"
